project:
  type: website
  render:
    - "*.qmd"
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto
  echo: true

website:
  page-navigation: true
  title: "Introduction to R and statistical packages in environmental epidemiology"
  description: "Homepage for the Introduction to R and statistical packages in environmental epidemiology"
  site-url: "https://ntluong95.quarto.pub/gothenburg_ws2025/"
  favicon: "images/jr-logo-circle.webp"

  repo-url: https://github.com/ntluong95/gothenburg_ws
  repo-actions: [source, edit, issue]

  page-footer:
    left: "&#169; 2025 Luong Nguyen Thanh"
    right: "Made with [Quarto Website](https://quarto.org)"
    background: "#0b7366"

  sidebar:
    background: "#0b7366"
    logo: "images/jr-logo-circle.webp"
    logo-alt: "A symbolic representation of the speaker"
    pinned: true
    align: center
    style: docked
    type: dark
    tools:
      - icon: github
        href: https://github.com/jadeynryan/parameterized-quarto-workshop
        text: GitHub
    contents:
     - href: index.qmd
       text: Home
     - href: prework.qmd
       text: Pre-work
     - href: license.qmd
       text: License

     - text: "---"
    #  - section: Slides

     - text: "Day 1"
       contents:
       - href: 1-welcome/index.qmd
         text: Introduction to R & Quarto
       - href: 2-dlnm/dlnm.qmd
         text: Statistical Methods in Environmental Epidemiology
     - text: "---"
    #  - section: Slides
     - text: "Day 2"
       contents:
       - href: 3-ggplot2/3-data-visualization.qmd
         text: Data visualization with ggplot2
       - href: 4-paper/heat_preterm-birth.qmd
         text: Journal club discussion



     - text: "---"
     - section: Exercies
       contents:
       - href: data/Miriam_analysis.qmd
         text: Example analysis from Miriam's data
       - href: data/Lea_analysis.qmd
         text: Example analysis from Lea's data
      #  - href: data/Linet_analysis.qmd
      #    text: Example analysis from Linet's data


format:
  html:
    theme: [flatly, theme.scss]
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    code-copy: true
    code-overflow: scroll
    mainfont: Atkinson Hyperlegible
    highlight-style: atom-one

  revealjs:
    author: "Luong Nguyen Thanh // April 28-29, 2025<br>Basic R // GU Workshop 2025"
    footer: "[ntluong95.quarto.pub/gothenburg_ws2025/](https://ntluong95.quarto.pub/gothenburg_ws2025)"
    logo: "images/jr-logo-circle.webp"
    logo-alt: "A symbolic representation of the speaker"
    width: 1600
    height: 900
    theme: slides.scss
    highlight-style: atom-one
    transition: fade
    slide-number: true
    df-print: kable

bibliography: references.bib  
# lightbox extension
# https://github.com/quarto-ext/lightbox
lightbox:
  desc-position: right  # position of description
  # match: auto # give all images lightbox treatment
  effect: zoom # how lightbox opens/closes
  loop: false # doesn't loop to first image in gallery
